DATA PRE-ANALYSIS AND DATA CLEANSING TEST

In [64]:
#IMPORT LIBRARY
import pandas as pd
import numpy as np 

# set options, show all the columns
pd. set_option("display.max_columns", None)

In [65]:
#Read file

df_raw= pd.read_parquet("../data_raw//iowa_liquor_sales_2019.parquet")

In [66]:
df_raw.head()

Invoice/Item Number        Date  Store Number  \
102        S08792800017  11/06/2019          2459   
103        S04854100048  04/03/2019          2487   
106        S08900500035  11/13/2019          4509   
110        S06855800032  07/31/2019          2522   
113        S08372100023  10/16/2019          3816   

                               Store Name  \
102                        Reinhart Foods   
103                  Anamosa Family Foods   
106                       A J'S LIQUOR II   
110  Hy-Vee Wine and Spirits / Spirit Lak   
113                                 Swils   

                                        Store Location  County Number  \
102        200 STATE PO BOX 98\nGUTHRIE CENTER 50115\n           39.0   
103  402 EAST MAIN\nANAMOSA 52205\n(42.108289, -91....           53.0   
106  2515 CHAMBERLAIN\nAMES 50010\n(42.02146, -93.6...           85.0   
110                HWY 9 &amp; 71\nSPIRIT LAKE 51360\n           30.0   
113  200 E OAK ST\nRED OAK 51566\n(41.016691, -95.2...           69.0   

         County   Category                       Category Name  Vendor Number  \
102     Guthrie  1062300.0                        FLAVORED RUM           65.0   
103       Jones  1081300.0                 PEPPERMINT SCHNAPPS          434.0   
106       Story  1081900.0  MISC. AMERICAN CORDIALS & LIQUEURS          322.0   
110   Dickinson  1062200.0    PUERTO RICO & VIRGIN ISLANDS RUM           35.0   
113  Montgomery  1031200.0                      VODKA FLAVORED          380.0   

                         Vendor Name  Item Number           Item Description  \
102                  Jim Beam Brands        44499           Cruzan Mango Rum   
103                   Luxco-St Louis        80578  Arrow Peppermint Schnapps   
106  Prestige Wine and Spirits Group        75210              Kinky Liqueur   
110             Bacardi U.S.A., Inc.        43125   Bacardi Superior Rum Pet   
113        Phillips Beverage Company        41693  Uv Blue (raspberry) Vodka   

     Pack  Bottle Volume (ml) State Bottle Cost State Bottle Retail  \
102    12                 750             $6.82              $10.24   
103     6                1750             $7.04              $10.56   
106     6                 750            $10.00              $15.00   
110    12                 750             $7.53              $11.30   
113    12                 750             $6.25               $9.49   

     Bottles Sold Sale (Dollars)  Volume Sold (Gallons)  
102             3         $30.72                   0.59  
103             3         $31.68                   1.39  
106            12        $180.00                   2.38  
110            12        $135.60                   2.38  
113            12        $113.88                   2.38

In [67]:
df_raw.shape

(2073616, 20)

In [68]:
# copy
df=df_raw.copy()

In [69]:
# convert the name of the columns into snake_case
df.columns= df.columns.str.replace(" ", "_").str.lower().str.replace("_(", "(")
df.sample()

invoice/item_number        date  store_number  \
2094639        S07588100020  09/06/2019          2567   

                           store_name  \
2094639  Hy-Vee Drugstore / Davenport   

                                            store_location  county_number  \
2094639  2200 WEST KIMBERLY\nDAVENPORT 52806\n(41.56015...           82.0   

        county   category   category_name  vendor_number vendor_name  \
2094639  Scott  1081200.0  CREAM LIQUEURS          305.0     MHW Ltd   

         item_number item_description  pack  bottle_volume(ml)  \
2094639        73052         Rumchata    12                375   

        state_bottle_cost state_bottle_retail  bottles_sold sale(dollars)  \
2094639             $7.41              $11.12            12       $133.44   

         volume_sold(gallons)  
2094639                  1.19

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2073616 entries, 102 to 8197504
Data columns (total 20 columns):
 #   Column                Dtype  
---  ------                -----  
 0   invoice/item_number   object 
 1   date                  object 
 2   store_number          int64  
 3   store_name            object 
 4   store_location        object 
 5   county_number         float64
 6   county                object 
 7   category              float64
 8   category_name         object 
 9   vendor_number         float64
 10  vendor_name           object 
 11  item_number           int64  
 12  item_description      object 
 13  pack                  int64  
 14  bottle_volume(ml)     int64  
 15  state_bottle_cost     object 
 16  state_bottle_retail   object 
 17  bottles_sold          int64  
 18  sale(dollars)         object 
 19  volume_sold(gallons)  float64
dtypes: float64(4), int64(5), object(11)
memory usage: 332.2+ MB


Data Transformation

data columns

In [71]:
df["date"]= pd.to_datetime(df["date"],
                          format="%m/%d/%Y")

float to integer column

In [72]:
#changes name to the column category
df["category_number"]=df["category"]
df.drop(columns="category",
        inplace=True)

In [73]:
df["county_number"].unique()

array([39., 53., 85., 30., 69., 57., 82., 96., 77., 31., 78., 52.,  9.,
       64., 49., 29., 34., 48., 63., 75., 97., 22., 46., 91.,  7., 70.,
       94., 10., 11., 56., 17., 71., 23., 50., 14., 67., 37., 86., 88.,
       40., 59., 51., 33., nan, 38., 72., 16., 21., 42., 35.,  3., 47.,
       90., 24.,  4., 95.,  6., 55., 20., 99., 32.,  5., 81., 45., 62.,
       25., 83., 60., 54., 41., 18., 84., 92., 28., 93.,  1., 44., 13.,
       58., 66.,  8., 15., 76., 79., 74., 19., 43., 12.,  2., 61., 73.,
       80., 65., 68., 87., 27., 36., 98., 89., 26.])

In [74]:
df["vendor_number"].unique()

array([ 65., 434., 322.,  35., 380., 260., 370., 192.,  55.,  85., 297.,
       389., 115., 451., 305., 395., 255., 461., 330., 420., 259., 410.,
       421., 885., 300., 205., 308., 240., 306., 357., 971., 294., 130.,
       390., 969., 301., 125., 277., 375., 267., 384., 418., 394., 365.,
       190., 285., 184., 338., 350., 492., 391., 198., 469.,  86., 160.,
       460., 962., 377., 978., 483., 239., 977., 250., 497., 495., 346.,
       399.,  89.,  10., 459., 295., 293., 154., 298., 158.,  91., 465.,
       415., 503.,  79., 369., 363., 987., 143., 307., 185., 224., 109.,
       211., 310., 379., 477.,  90., 108., 313.,  61., 278., 501., 251.,
        80., 311., 482., 456., 137., 361., 475., 287., 488.,  27., 485.,
       803.,  68., 432., 263., 155.,  69., 343., 161., 486.,  51.])

I check that the values should be integral and not float. Transform into the column that we can that has no nulls.

In [75]:
#transform vendor_number because not have nulls
df["vendor_number"]= df["vendor_number"].astype(int)

In [76]:
df["vendor_number"].unique()

array([ 65, 434, 322,  35, 380, 260, 370, 192,  55,  85, 297, 389, 115,
       451, 305, 395, 255, 461, 330, 420, 259, 410, 421, 885, 300, 205,
       308, 240, 306, 357, 971, 294, 130, 390, 969, 301, 125, 277, 375,
       267, 384, 418, 394, 365, 190, 285, 184, 338, 350, 492, 391, 198,
       469,  86, 160, 460, 962, 377, 978, 483, 239, 977, 250, 497, 495,
       346, 399,  89,  10, 459, 295, 293, 154, 298, 158,  91, 465, 415,
       503,  79, 369, 363, 987, 143, 307, 185, 224, 109, 211, 310, 379,
       477,  90, 108, 313,  61, 278, 501, 251,  80, 311, 482, 456, 137,
       361, 475, 287, 488,  27, 485, 803,  68, 432, 263, 155,  69, 343,
       161, 486,  51])

Transform Price Values

    -state_bottle_cost 
    -state_bottle_retail
    -sale(dollars)

In [ ]:
def dollars_float(dataframe,col):
    dataframe[col]= dataframe[col].str.replace("$","").astype(float)
    return dataframe


In [80]:
list_col= ["state_bottle_cost", "state_bottle_retail","sale(dollars)"]
for col in list_col:
    dollars_float(df, col)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2073616 entries, 102 to 8197504
Data columns (total 20 columns):
 #   Column                Dtype         
---  ------                -----         
 0   invoice/item_number   object        
 1   date                  datetime64[ns]
 2   store_number          int64         
 3   store_name            object        
 4   store_location        object        
 5   county_number         float64       
 6   county                object        
 7   category_name         object        
 8   vendor_number         int64         
 9   vendor_name           object        
 10  item_number           int64         
 11  item_description      object        
 12  pack                  int64         
 13  bottle_volume(ml)     int64         
 14  state_bottle_cost     float64       
 15  state_bottle_retail   float64       
 16  bottles_sold          int64         
 17  sale(dollars)         float64       
 18  volume_sold(gallons)  float64       
 19  cat

Column decomposition store_location

In [85]:
value_store_location= df["store_location"].iloc[1]
value_store_location

'402 EAST MAIN\nANAMOSA 52205\n(42.108289, -91.281881)'

In [96]:
address= value_store_location.split("\n")[0]
city= value_store_location.split("\n")[1].split (" ")
Latitude= float(value_store_location.split("\n")[2].strip("()").split(",")[0])
longitude= float(value_store_location.split("\n")[2].strip("()").split(", ")[1])


In [99]:
def extract_location(value):
    try : 
        split_data=value.split("\n")
        address = split_data[0]
        city=split_data[1]
        if len (split_data)> 2 and split_data[2].strip():
            latitude,longitude= map(float, split_data[2].strip("()").split(", "))
        else: 
            latitude, longitude = None, None
        return pd.Series([address, city, latitude, longitude])
    except(IndexError,ValueError):
        return pd.Series([None,None,None])

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2073616 entries, 102 to 8197504
Data columns (total 24 columns):
 #   Column                Dtype         
---  ------                -----         
 0   invoice/item_number   object        
 1   date                  datetime64[ns]
 2   store_number          int64         
 3   store_name            object        
 4   store_location        object        
 5   county_number         float64       
 6   county                object        
 7   category_name         object        
 8   vendor_number         int64         
 9   vendor_name           object        
 10  item_number           int64         
 11  item_description      object        
 12  pack                  int64         
 13  bottle_volume(ml)     int64         
 14  state_bottle_cost     float64       
 15  state_bottle_retail   float64       
 16  bottles_sold          int64         
 17  sale(dollars)         float64       
 18  volume_sold(gallons)  float64       
 19  cat

In [100]:
df[["address",
    "city",
    "Latitude",
    "longitude"]]= df["store_location"].apply(extract_location)

In [105]:
df.to_parquet("../data_transformation/dataset_cleaned.parquet")